steps:

  - id: decipher secret
    name: gcr.io/cloud-builders/gcloud
    args:
    - kms
    - decrypt
    - "--ciphertext-file=secret.yaml.encrypted"
    - "--plaintext-file=secret.yaml"
    - "--location=$_GKE_LOCATION"
    - "--keyring=jeremy-key-ring"
    - "--key=hello-world-k8s"

  - id: Generate application configMap
    name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'configmap.yaml', '--namespace', '$_K8S_NAMESPACE']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_GKE_LOCATION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER'
    
  - id: Build
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args: ["-c", "docker build -t asia.gcr.io/effective-might-323902/hello-world-k8s-prohmpossadhorn . -f Dockerfile"]

  - id: Push
    name: gcr.io/cloud-builders/docker
    args: ["push", "asia.gcr.io/effective-might-323902/hello-world-k8s-prohmpossadhorn"]

  - id: Apply deploy
    name: gcr.io/cloud-builders/gke-deploy
    args: ["apply", "--filename=kube-deployment.yml", "--namespace=default"]
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_GKE_LOCATION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER'

options:
  substitutionOption: ALLOW_LOOSE
tags:
  - devops-workshop
  - hello-world-k8s